### ISSUE TITLE
add a "batch" mode

### ISSUE THREAD

**Issue by fbaligand** [fabiopipitone/elasticsearch-tocsv#1]
add an option to run the tool with no interaction: no ask for login/password, no ask for output file overwrite, etc...

**Comment by fabiopipitone** [comment]
Very interesting. I actually arranged the -pw and -spw options to let the user the possibility to run the script without interaction but I didn't thought about the confirmation in case of overwriting a file or proceeding without ssl certificate verification or similar or the case when a user wants to run the tool in batch mode without any authentication required (you could still specify a empty -pw field but it would be counter-intuitive) . 

I added a -sm/--silent_mode so the user can run the script without any interaction. A warning will be printed out in case this option is enabled (just to remind you that you won't have for example the possibility to stop a file overwriting) and then the script just keeps running. If you forgot to set a pw or you specify an already existing export path, you could have thought about it in the first place :)

Thanks for the enhancement suggestion
