### ISSUE TITLE
add a "column_separator" option

### ISSUE THREAD

**Issue by fbaligand** [fabiopipitone/elasticsearch-tocsv#2]
In some cases, this is useful to have another separator than ",".
For example: to open CSV file with Microsoft Excel, french edition.

**Comment by fabiopipitone** [comment]
Sounds good. I just added a -cs/--csv_separator option to specify which character to use as column separator. I decided to add to the description the warning you can find in the pandas docs about using multiple characters separators.

Thanks for the idea
