### ISSUE TITLE
add an option to specify number locale or explicit decimal separator

### ISSUE THREAD

**Issue by fbaligand** [fabiopipitone/elasticsearch-tocsv#6]
It is useful to have a way to customize decimal separator given user locale, especially to open CSV file in Microsoft Excel.
So, an option like "number_locale" or "decimal_separator" would be great!

**Comment by fabiopipitone** [comment]
Guess it pairs with the column separator suggestion :)

Anyway it's a good idea. I added it in the -ds/--decimal_separator option, alongside the possibility to choose the decimal rounding in the -dr/--decimal_rounding option.
